### ISSUE TITLE
Idea: put all-cabal-files in ~/.stackage/update/ instead of ~/.stackage-update/

### ISSUE THREAD

**Issue by DanBurton** [fpco/stackage-update#6]
It seems nice for the user if stackage plugins all put their stuff in the same tree.

Sometime soon, `Stackage.CLI` will provide the `getStackageRootIO :: IO FilePath` function (currently defined in stackage-setup only), and it might be advisable to use that.

**Comment by snoyberg** [comment]
I'm not sure I see this as a win, it seems decidedly in the "I wouldn't care personally" category. Maybe others have a thought on this?

**Comment by rvion** [comment]
+1 for **same root folder**

I think that having all stackage related plugins share the same dedicated folder is more extensible, more rememberable, and could prevent later problems.

Random hypothetical bonus of having one common folder:
- sharing the folder with some docker container
- clean uninstall with `rm -rf $STACKAGE_ROOT` or  `rm -rf ~/.stackage` (note that symlinks would not allow that behaviour)
- versioning the whole folder to know what changed (git subfolder would automatically be handled nicely by git)
- allowing the folder to be placed in an usual place for non regular systems with read only folders / disk
- allowing the folder to be placed in an ssd disk instead of an regular drive

**Comment by snoyberg** [comment]
Change made
